services:
  db:
    image: pgvector/pgvector:pg16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: menuwhisper
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 5s
      timeout: 5s
      retries: 20

  redis:
    image: redis:7
    ports:
      - "6379:6379"

  minio:
    image: minio/minio:latest
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"

  api:
    build:
      context: ../apps/api
      dockerfile: Dockerfile
    environment:
      APP_ENV: docker
      DB_URL: postgresql+psycopg://postgres:postgres@db:5432/menuwhisper
      REDIS_URL: redis://redis:6379/0
      CORS_ORIGINS: http://localhost:3000
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8000:8000"