"""add embeddings and user feedback tables

Revision ID: 5cf3c04026de
Revises: 3320ccd52313
Create Date: 2025-01-06 10:30:00.000000

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "5cf3c04026de"
down_revision: Union[str, None] = "3320ccd52313"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "menu_item_embeddings",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("menu_item_id", sa.UUID(), nullable=False),
        sa.Column("embedding", sa.ARRAY(sa.Float()), nullable=False),
        sa.Column("embedding_model", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["menu_item_id"], ["menu_items.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_menu_item_embeddings_id"), "menu_item_embeddings", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_menu_item_embeddings_menu_item_id"),
        "menu_item_embeddings",
        ["menu_item_id"],
        unique=False,
    )

    op.create_table(
        "user_feedback",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("user_id", sa.String(), nullable=False),
        sa.Column("menu_item_id", sa.UUID(), nullable=False),
        sa.Column("liked", sa.Boolean(), nullable=False),
        sa.Column("rating", sa.Integer(), nullable=True),
        sa.Column("review_text", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["menu_item_id"], ["menu_items.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_user_feedback_id"), "user_feedback", ["id"], unique=False)
    op.create_index(
        op.f("ix_user_feedback_menu_item_id"),
        "user_feedback",
        ["menu_item_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_user_feedback_user_id"), "user_feedback", ["user_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_user_feedback_user_id"), table_name="user_feedback")
    op.drop_index(op.f("ix_user_feedback_menu_item_id"), table_name="user_feedback")
    op.drop_index(op.f("ix_user_feedback_id"), table_name="user_feedback")
    op.drop_table("user_feedback")
    op.drop_index(
        op.f("ix_menu_item_embeddings_menu_item_id"), table_name="menu_item_embeddings"
    )
    op.drop_index(op.f("ix_menu_item_embeddings_id"), table_name="menu_item_embeddings")
    op.drop_table("menu_item_embeddings")
    # ### end Alembic commands ###
