FROM python:3.11-slim
WORKDIR /app
RUN pip install --no-cache-dir poetry==1.8.3
COPY pyproject.toml poetry.lock* ./
RUN poetry config virtualenvs.create false && poetry install --no-interaction --no-ansi
COPY . .
# Run migrations at start
CMD alembic upgrade 3320ccd52313 && uvicorn app.main:app --host 0.0.0.0 --port 8000